CREATE TABLE `prefix_ebcms_cms_category` (
 `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '节点ID',
 `title` varchar(255) NOT NULL DEFAULT '' COMMENT '标题',
 `name` varchar(255) NOT NULL COMMENT '名称',
 `keywords` varchar(255) NOT NULL DEFAULT '' COMMENT '关键字',
 `description` varchar(255) NOT NULL DEFAULT '' COMMENT '简介',
 `tpl_category` varchar(255) NOT NULL DEFAULT '' COMMENT '模板',
 `tpl_content` varchar(255) NOT NULL DEFAULT '' COMMENT '内容页模板',
 `priority` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '排序',
 `state` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '是否发布',
 `nav` tinyint(3) unsigned NOT NULL DEFAULT '1',
 `content_priority` tinyint(3) unsigned NOT NULL DEFAULT '2' COMMENT '是否允许内容排序',
 `redirect_uri` varchar(255) NOT NULL DEFAULT '' COMMENT '外部链接',
 `filters` text NOT NULL,
 `fields` text NOT NULL,
 PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=COMPACT COMMENT='内容栏目表';
CREATE TABLE `prefix_ebcms_cms_content` (
 `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '节点ID',
 `category_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '分类id',
 `title` varchar(255) NOT NULL DEFAULT '' COMMENT '标题',
 `cover` varchar(255) NOT NULL DEFAULT '' COMMENT '缩略图',
 `keywords` varchar(255) NOT NULL DEFAULT '' COMMENT '关键词',
 `description` varchar(255) NOT NULL DEFAULT '' COMMENT '摘要',
 `body` text NOT NULL,
 `extra` text NOT NULL,
 `alias` varchar(255) NOT NULL DEFAULT '' COMMENT '文件名称',
 `tpl` varchar(255) NOT NULL DEFAULT '' COMMENT '模板',
 `click` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '点击量',
 `tags` varchar(255) NOT NULL DEFAULT '',
 `top` tinyint(3) unsigned NOT NULL DEFAULT '0',
 `priority` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '优先权',
 `create_time` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '操作时间',
 `update_time` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '更新时间',
 `state` tinyint(3) unsigned NOT NULL DEFAULT '99' COMMENT '状态',
 `redirect_uri` varchar(255) NOT NULL DEFAULT '',
 `filter0` text NOT NULL,
 `filter1` text NOT NULL,
 `filter2` text NOT NULL,
 `filter3` text NOT NULL,
 `filter4` text NOT NULL,
 `filter5` text NOT NULL,
 PRIMARY KEY (`id`) USING BTREE,
 KEY `list` (`category_id`,`state`,`id`) USING BTREE,
 KEY `list2` (`state`,`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;